# courtesy of https://github.com/bradtraversy/docker-node-mongo

version: '3'

services:
  app:
    container_name: insidero
    build: .
    ports:
      - '83:3000'
      - '3002:3003'
    links:
      - mongo
    volumes:
      - ../../:/usr/src/app/
      - ./run.sh:/run.sh
      - app-node-modules:/usr/src/app/node_modules/

  mongo:
    container_name: insidero-mongo
    image: mongo
    expose:
      - '27017'

volumes:
  app-node-modules: